# returning error
GET http://localhost:3500/blahblah
Accept: application/json

###
# returning errors
GET http://localhost:3500/blahblah
Accept: text/html

###

# returns all employees
GET http://localhost:3500/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOls1MTUwLDE5ODQsMjAwMV19LCJpYXQiOjE3MDY3OTgxMTEsImV4cCI6MTcwNjc5ODE3MX0.vtphivVpJJrhJHDFMBbPxdSOCX3sA7nW5PeltYN59XA

###

# creates new employee
POST http://localhost:3500/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOls1MTUwLDE5ODQsMjAwMV19LCJpYXQiOjE3MDY3OTgxMTEsImV4cCI6MTcwNjc5ODE3MX0.vtphivVpJJrhJHDFMBbPxdSOCX3sA7nW5PeltYN59XA

{
    "firstname": "Saeid",
    "lastname": "Mo"
}

###

# updates an existing employee
PUT http://localhost:3500/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImVkaXRvciIsInJvbGVzIjpbMTk4NCwyMDAxXX0sImlhdCI6MTcwNjc5Nzk1MSwiZXhwIjoxNzA2Nzk4MDExfQ.VWRRv1gvP1D6m7LXwblkDfFOXh8k4gC-r7oYzP_Q9po

{
    "id": 3,
    "firstname": "Saeid",
    "lastname": "Mohadjer"
}

###

DELETE http://localhost:3500/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOls1MTUwLDE5ODQsMjAwMV19LCJpYXQiOjE3MDY3OTgxMTEsImV4cCI6MTcwNjc5ODE3MX0.vtphivVpJJrhJHDFMBbPxdSOCX3sA7nW5PeltYN59XA

{
    "id": 3
}

###

GET http://localhost:3500/employees/1

###

#register
POST http://localhost:3500/register
Content-Type: application/json

{
    "username": "admin",
    "password": "test"

}

###

#login
POST http://localhost:3500/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

# returns an accessToken if you call it after login so that jwt cookie is sent automatically in this request
GET http://localhost:3500/refresh


###

#logout
GET http://localhost:3500/logout

